name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  fourcipp-code-check:
    name: Code check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up virtual environment and install fourcipp with requirements
        uses: ./.github/actions/setup-env
        with:
          python-version: 3.13
      - name: Install requirements
        run: |
          pip install pre-commit
      - name: Run code-checks
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            SKIP=no-commit-to-branch pre-commit run --all-files
          else
            pre-commit run --all-files
          fi
