name: Update 4C metadata and schema file

# execute each morning and on every PR

on:
  schedule:
    - cron: '0 5 * * *' # run each night at 5AM. Current nightly 4C test should be completed by then
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update-4C-metadata-schema-file:
    name: Update 4C metadata and schema file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull latest metadata file from 4C
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.ORGANIZATION_TOKEN }}
          workflow: nightly_tests.yml
          workflow_conclusion: completed
          name: clang18_build-metadata
          path: clang18_build-metadata
      - name: Pull latest schema file from 4C
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.ORGANIZATION_TOKEN }}
          workflow: nightly_tests.yml
          workflow_conclusion: completed
          name: clang18_build-schema
          path: clang18_build-schema
      - name: Check if metadata file has changed and overwrite old file if necessary
        run: |
          set -euo pipefail
          hash_current=$(grep -v 'commit_hash' src/fourcipp/config/4C_metadata.yaml | sha256sum | awk '{print $1}')
          hash_new=$(grep -v 'commit_hash' clang18_build-metadata/4C_metadata.yaml | sha256sum | awk '{print $1}')

          echo "Current metadata file hash: $hash_current"
          echo "New metadata file hash:     $hash_new"

          if [ "$hash_current" != "$hash_new" ]; then
              mv clang18_build-metadata/4C_metadata.yaml src/fourcipp/config/4C_metadata.yaml
              mv clang18_build-schema/4C_schema.json src/fourcipp/config/4C_schema.json
              rm -r clang18_build-metadata
              rm -r clang18_build-schema

              echo "metadata_file_changed=true" >> $GITHUB_ENV
          else
              echo "metadata_file_changed=false" >> $GITHUB_ENV
          fi
      # Format new files with pre-commit
      - name: Set up virtual environment
        if: env.metadata_file_changed == 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true
          activate-environment: fourcipp
          python-version: 3.12
      - name: Install requirements
        if: env.metadata_file_changed == 'true'
        shell: bash -el {0}
        run: |
          conda activate fourcipp
          pip install -e .[dev]
          pip install pre-commit
      - name: Run pre-commit, i.e., format files
        if: env.metadata_file_changed == 'true'
        shell: bash -el {0}
        run: |
          conda activate fourcipp
          SKIP=no-commit-to-branch pre-commit run --all-files
      # Commit and push changes
      - name: Get 4C hash for commit message
        if: env.metadata_file_changed == 'true'
        run: echo "fourc_commit_hash=$(awk '/commit_hash:/ {print $2}' src/fourcipp/config/4C_metadata.yaml)" >> $GITHUB_ENV
      - name: Commit and push changes
        if: env.metadata_file_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            Nightly update 4C metadata and schema file

            Corresponding 4C commit hash: ${{ env.fourc_commit_hash }}
          branch: main
          commit_options: '--no-verify'
          commit_user_name: Nightly 4C metadata update
